import './globals.css'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Google',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link  rel="icon" href="/icon.svg" sizes="<generated>" type="image/<generated>"/>
      </head>
      <body className='relative min-h-screen'>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
